version: '2'
services:
    db:
        image: mariadb
        restart: always
        volumes:
          - ./data:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: medportal
        ports:
          - "3306:3306"
    php:
        build: .
        volumes:
          - .:/var/www/site
        depends_on:
          - db
        ports:
          - "8080:80"